- .gitignore
- Vagrantfile
- examples/commit-message-3
- examples/commit-message-4
- examples/commit-message-5
- gitlint/config.py
- gitlint/rules.py
Hi,
Thanks for gitlint, trying it out in our project! :)
This pull-request fixes some things in the Vagrantfile and adds three new tests for violations I've seen in our project previously.
tobyox@cisco.com
> Fix Vagrantfile and some new tests

- gitlint/tests/test_body_rules.py
- gitlint/tests/test_title_rules.py
Unit tests for the rules:
* BodyMissing,
* BodyMinLength and
* TitleLeadingWhitespace
> Test BodyMissing, BodyMinLength, TitleLeadingWhitespace

- gitlint/tests/base.py
- gitlint/tests/test_cli.py
- gitlint/tests/test_config.py
- gitlint/tests/test_config_builder.py
- gitlint/tests/test_config_precedence.py
- gitlint/tests/test_display.py
- gitlint/tests/test_git.py
- gitlint/tests/test_hooks.py
- gitlint/tests/test_lint.py
- gitlint/tests/test_options.py
- requirements.txt
- setup.py
Hi,
I would like to create a package for Debian, therefore I came across some problems that need these fixes. The detailed information about the fixes are in the respective commits.
Here is the related "intend to package" (ITP) bug: https://bugs.debian.org/886864
Best
Patrik
> Fixes for Debian packaging

- .travis.yml
- docs/index.md
- gitlint/cli.py
- gitlint/git.py
- gitlint/shell.py
- gitlint/tests/base.py
- gitlint/tests/test_cli.py
- gitlint/tests/test_git.py
- gitlint/utils.py
- qa/base.py
- qa/expected/debug_output1
- qa/test_config.py
- run_tests.sh
- setup.py
Experimental support for Windows (known issues can be found on the issue
tracker).
Related to #20 and heavily influenced by #71.
> Windows support (experimental)

- gitlint/rules.py
- requirements.txt
Hopefully this is easy to merge in, I'll try to polish the documentation a bit too ..
> Minor cleanups, typo and regexp fixes

- examples/gitlint
- gitlint/files/gitlint
I think these changes would have made it much more easy for me. What do you think?
I also changed default lengths to follow 50/72 rule, hope you don't mind ;)
> Tweaked example configuration files

- gitlint/tests/rules/test_configuration_rules.py
- gitlint/tests/test_utils.py
- gitlint/utils.py
- qa/base.py
- qa/shell.py
- qa/test_commits.py
- qa/test_config.py
- qa/test_contrib.py
- qa/test_gitlint.py
- qa/test_hooks.py
- qa/test_stdin.py
- qa/test_user_defined.py
- qa/utils.py
- tools/create-test-repo.sh
- tools/win-create-test-repo.bat
> Windows fixes

- CHANGELOG.md
- docs/configuration.md
- docs/contrib_rules.md
- docs/contributing.md
- docs/extra.css
- docs/index.md
- docs/rules.md
- docs/user_defined_rules.md
- gitlint/cli.py
- gitlint/files/gitlint
- mkdocs.yml
- run_tests.sh
- Reviewed and cleaned up all documentation
- Updated CHANGELOG for upcoming 0.13.0 release
- Added some more stats to ./run_tests.sh :-)
> Documentation updates

- Dockerfile
- Dockerfile.dev
- docs/index.md
- run_tests.sh
Images published on:
https://hub.docker.com/r/jorisroovers/gitlint
> Docker images for end-users

- .github/workflows/checks.yml
- run_tests.sh
This should catch issues before they are merged.
Relates to #134
> Check runs are now also trigged by PRs

- CHANGELOG.md
- docs/index.md
- gitlint/config.py
- gitlint/tests/cli/test_cli.py
- gitlint/tests/config/test_config_builder.py
- gitlint/tests/expected/test_cli/test_named_rules_1
- gitlint/tests/expected/test_cli/test_named_rules_2
- gitlint/tests/samples/config/named-rules
- gitlint/tests/test_lint.py
- qa/expected/test_named_rules/test_named_rule_1
- qa/expected/test_named_rules/test_named_user_rule_1
- qa/expected/test_user_defined/test_user_defined_rules_extra_1
- qa/samples/config/named-rules
- qa/samples/config/named-user-rules
- qa/samples/user_rules/extra/extra_rules.py
- qa/test_named_rules.py
- qa/test_user_defined.py
Named rules allow users to have multiple of the same rules active at the same
time, which allows them to enforce the same rule multiple times but with
different options.
Implements #113
Relates to #66
> Named Rules

- .github/workflows/checks.yml
- CHANGELOG.md
- Dockerfile
- Vagrantfile
- run_tests.sh
- setup.py
Adds python 3.9 Support
Implements #152
> Python 3.9 Support

- .pre-commit-hooks.yaml
- docs/index.md
> Fix pre-commit hook config

- gitlint/cli.py
- gitlint/config.py
- gitlint/git.py
- gitlint/options.py
- gitlint/shell.py
- gitlint/tests/base.py
- gitlint/tests/cli/test_cli.py
- qa/base.py
- qa/requirements.txt
- qa/shell.py
- qa/test_hooks.py
- requirements.txt
- setup.py
- test-requirements.txt
> Dependency upgrades

- CHANGELOG.md
- docs/configuration.md
- docs/contributing.md
- docs/index.md
- docs/rules.md
- mkdocs.yml
- setup.py
- Updated Changelog
- Added more project links to setup.py
- Minor user-facing doc updates
> Doc updates

- docs/contrib_rules.md
Just a typo in the documentation.
> Fix contrib-body-requires-signed-off-by

- docs/contributing.md
A few tweaks to the local development environment setup docs.
> docs: Use standard virtualenv setup instructions

- run_tests.sh
This is already in `.coveragerc`.
> chore: Remove duplicate coverage configuration

- .github/workflows/checks.yml
- Dockerfile
- setup.py
Officially adding support for Python 3.10.
> Python 3.10 support

- gitlint/files/gitlint
> Fix typo in default gitlint

- docs/rules.md
> Update incorrect uses of 'title' in docs/rules.md

- .github/workflows/checks.yml
Required some minor syntax changes to pypy version strings.
> Updated actions/setup-python from 2 to 3.1.1

- .github/workflows/checks.yml
- qa/test_hooks.py
Short on time now, will double check code and update issue before
merging this.
> github CI fix: no tty attached to stdin

- docs/rules.md
> Fix descriptions of length config parameters

- docs/index.md
- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/git.py
- gitlint-core/gitlint/tests/git/test_git_commit.py
- qa/expected/test_commits/test_csv_hash_list_1
- qa/test_commits.py
Support for --commits flag
Closes #283
> Issue 248 multiple commits

- .github/workflows/checks.yml
- gitlint-core/setup.py
- setup.py
- test-requirements.txt
Support for Python 3.11 (RC2).
> Python 3.11 support

- CHANGELOG.md
Changelog update for the upcoming 0.18.0 release.
> Changelog update for 0.18.0

- .github/workflows/checks.yml
Attempt to fix integration tests
> Revert fix for integration test issues in GHA

- .coveragerc
- pyproject.toml
Also moved the coverage config to pyproject.toml
> Use pytest-cov instead of coverage

- docs/contributing.md
- gitlint-core/gitlint/lint.py
- pyproject.toml
Mention of autoformat and autofix hatch scripts.
> Docs: tweak contributing docs

- gitlint-core/pyproject.toml
- pyproject.toml
Aligned with VSCode extension Even-Better-TOML which uses tamasfe/taplo.
> Reformat pyproject.toml files

- .github/workflows/checks.yml
Windows testing now also happens on all supported Python versions.
> GHA: Remove duplicate windows config

- .github/workflows/test-release.yml
Allows testing released gitlint versions.
> Post-release GHA testing workflow

- .github/workflows/test-release.yml
Added workflow inputs for:
- PyPI repository to use
- Git reference to checkout for integration tests
> GHA: Test Release worfklow improvements

- .devcontainer/devcontainer.json
Added extra extensions, configured black.
> Devcontainer improvements

- gitlint-core/gitlint/config.py
- gitlint-core/gitlint/hooks.py
- gitlint-core/gitlint/rule_finder.py
- gitlint-core/gitlint/rules.py
- gitlint-core/gitlint/shell.py
- pyproject.toml
- qa/base.py
- qa/shell.py
Fixed or supressed new violations.
> Update ruff to 0.0.244

- gitlint-core/gitlint/cli.py
This comment no longer makes sense in the current codebase.
> Remove outdated comment line in cli.py

- .github/workflows/publish-docker.yml
- .github/workflows/publish-release.yml
Various improvements to the publish-docker workflow.
> GHA: publish-docker workflow improvements

- CHANGELOG.md
- tools/changelog.py
- Updated changelog for upcoming 0.19.0 release
- Changed CHANGELOG format with more headers
- Simple changelog.py script that generates rough changelog outline
> Changelog updates

- gitlint-core/gitlint/config.py
- pyproject.toml
- pytest: 7.2.0 -> 7.2.1
- black: 22.10.0 -> 23.1.0
- ruff: 0.0.244 -> 0.0.252
- pdr: 0.7.5 -> 0.8.2
> Update test dependencies

- .github/workflows/checks.yml
- README.md
- pyproject.toml
Needs more work and cleanup. First trying to get this to work.
> Fix coveralls reporting

- .github/workflows/ci.yml
- .github/workflows/github-release.yml
- Renamed checks.yml to ci.yml
- Add concurrency control to ci to auto-cancel outdated ci runs
- Publish releases to pypi instead of test.pypi.org
> GHA: Minor tweaks

- .github/workflows/test-docker.yml
Allows for post-release testing of docker images.
> GHA: Test Docker workflow

- .github/workflows/ci.yml
- .github/workflows/github-release.yml
- .github/workflows/publish-docker.yml
- .github/workflows/publish-release.yml
- .github/workflows/test-docker.yml
Also run the Test Docker workflow after publishing a new docker image.
> GHA: Docker Test workflow improvements

- gitlint-core/gitlint/cli.py
--msg-filename type is now a Path and not a managed click.File.
This makes it easier to control the opening and closing of the file.
Context manager will make sure that the file we use will be refreshed after
edition.
> Fix msg-filename kept open after edition

- docs/contributing/tests_formatting_docs.md
- docs/javascript/extra.js
- mkdocs.yml
- pyproject.toml
Use of mike to publish different versions of the docs
> Mike for docs versioning

- .github/workflows/publish-docs.yml
Adds git user.name and user.email config required for mike to push to
the gh-pages branch.
> GHA: Fix for publish-docs workflow

- .github/workflows/ci.yml
- .github/workflows/publish-release.yml
Use GHA to leave a comment with on a PR after its merged
with a link to the corresponding dev build on PyPI and instructions
on how to install it.
> GHA: Comment dev build numbers on PR after merge

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Various cleanup and minor tweaks to the devcontainer.
> Devcontainer tweaks
