- Vagrantfile
- gitlint/tests/test_hooks.py
When I ran run_tests.sh I got the error in the commit. So this should fix that. I'm completely new to mock etc. so excuse any mistake. I've use ANY because I have no idea how I should mock the stat response, I think that should do for now. Now that I look at it, perhaps I should have use patch.ANY instead of importing ANY.
Since I've been destroying the vagrant so frequently I've make use of the vagrant-cachier plugin so I don't have to re-download packages. The change should have no impact for people without the plugin. It is completely optional.
> Fix test_install_commit_msg_hook

- examples/commit-message-6
- gitlint/rules.py
- gitlint/tests/test_body_rules.py
B6 (body-is-missing) should be ignored when the commit is a merge commit.
Merge commits can be generated by automated systems like Gerrit and
those systems copy the title from the source commit but may not copy the
body. commit-message-6 gives an example.
> Ignore B6 when merge commit

- gitlint/config.py
- requirements.txt
- setup.py
Python 2.6 support
We have a project that uses Python 2.6 and would like 
to use this tool to verify our commit messages.
This PR imports `OrderedDict` from the `ordereddict` 
package if the built-in from `collections` is not present.
> Python 2.6 support

- gitlint/cli.py
- gitlint/tests/test_cli.py
add --debug option and suppress the "Using config from ..." command line
log when --debug is not set.   This should make gitlint silent when the
comment passed to it is well-formed, but nicely verbose by default on
any errors.
> Add --debug option

- gitlint/rules.py
- gitlint/tests/test_title_rules.py
the violation message when a title did not match the expected regex was
inverted, e.g. it said that the title "does match" when it should have
been "does not match"
> fix inverted violation message

- gitlint/cli.py
- gitlint/git.py
- gitlint/tests/test_cli.py
- gitlint/tests/test_git.py
> Add support for linting a range of commits natively.

- gitlint/cli.py
- gitlint/tests/test_cli.py
This fixes a "index out of range" exception when the specified git range for --commits is empty.
Fixes #22.
> Handle empty commit list in --commits (#22)

- docs/user_defined_rules.md
- gitlint/cli.py
- gitlint/config.py
- gitlint/options.py
- gitlint/tests/test_config.py
- gitlint/tests/test_options.py
- gitlint/tests/test_user_rules.py
- gitlint/user_rules.py
The --extra-path option now allows user defined rules to be either a file or directory.
Fixes #26.
> Accept either a file or directory for the --extra-path option (#26)

- gitlint/git.py
- gitlint/tests/samples/commit_message/sample1
- gitlint/tests/test_git.py
Fix cleaning up commit message when `git commit -v` command used.
Git adds special cutline (scissors) when using with `-v` arg. Lines after this one will not be included to commit
See [--verbose arg description](https://git-scm.com/docs/git-commit#git-commit---verbose) and [scissors clean up](https://git-scm.com/docs/git-commit#git-commit-scissors) description in docs for details
Also add handle of custom comment char [see `core.commentChar` setting](https://git-scm.com/docs/git-config#git-config-corecommentChar)
> Add handle of git scissors cleanup and custom comment char

- CHANGELOG.md
- gitlint/cli.py
- gitlint/git.py
- gitlint/tests/test_cli.py
- gitlint/tests/test_git.py
- qa/base.py
- qa/test_commits.py
Gitlint did not correctly handle all refspec formats that were supported
by `git rev-list`. It does now :)
This fixes #23.
> Gitlint now correctly handles refspec

- gitlint/git.py
- gitlint/tests/test_cli.py
- gitlint/tests/test_git.py
We have had a few users with names formatted as "Surname, GivenName" that would cause git lint to error. In order to remedy this, I modified the delimiter to be a nul byte (which should never occur) for the git log --pretty command.
> Prevent Commas in text fields from breaking git log printing

- .pylintrc
- gitlint/cli.py
- gitlint/tests/test_cli.py
- gitlint/tests/test_config_precedence.py
- qa/base.py
- qa/test_commits.py
- qa/test_config.py
- qa/test_gitlint.py
- qa/test_hooks.py
- qa/test_user_defined.py
Before this commit, gitlint defaulted to reading the latest commit message
from the local git repository when it found a TTY connected to STDIN,
falling back to reading from STDIN in all other cases.
With this commit, gitlint will do the opposite which is more sane: it will
only read from STDIN in case there's input on STDIN, falling back to reading
from the local git repo in all other cases.
This is especially useful for environments where there is no TTY attached to
STDIN like in many CI environments.
This fixes #40, #42.
> No longer require a TTY connected to STDIN to read from local git repo

- gitlint/tests/test_cli.py
The test_target test case calls git and expect a certain error message in English. If a different languages is use, git might produce a translated error message that does not match the expected error message. Therefore set the environment variable `LANGUAGE=C`.
> Enforce English in test_target

- gitlint/git.py
- gitlint/tests/test_git.py
As soon as _git function returns string if it was executed (not sh.RunningCommand) **get_commentchar**
functions fails with AttributeError (could not get exit_code).
> Fix failing on existing Git comment char

- gitlint/cli.py
- gitlint/files/commit-msg
- gitlint/tests/test_cli.py
The --msg-filename option enables the following:
- Easier checking in a commit-msg hook without requiring a `cat` process.
- Easy integration with http://pre-commit.com
This is related to #38
> Add --msg-filename option

- .pre-commit-hooks.yaml
- docs/index.md
This enables out-of-the-box usage with https://pre-commit.com as a commit-msg
hook.
Resolves #38
> Add pre-commit metadata

- gitlint/cli.py
- gitlint/tests/test_cli.py
Reduce confusion on whether the lint check is successful/failed.
> Exit silently when the specified commit range is empty

- .pre-commit-hooks.yaml
Removed the `stages` line from `.pre-commit-hooks.yaml`, and made a slight re-ordering to conform to the `pre-commit` docs.  The `stages` line belongs in `.pre-commit-config.yaml` instead.
> Removed erroneous 'stages' line from .pre-commit-hooks.yaml

- .pre-commit-hooks.yaml
This reverts commit f3906027abb1fd434e9c92b1c7050bf146b3121a.
See https://github.com/jorisroovers/gitlint/pull/64#issuecomment-381410128
> Revert "Removed erroneous 'stages' line from .pre-commit-hooks.yaml (#64)"

- .pylintrc
- .travis.yml
- gitlint/cli.py
- gitlint/git.py
- gitlint/lint.py
- gitlint/rules.py
- gitlint/user_rules.py
- gitlint/utils.py
- qa/base.py
- qa/requirements.txt
- qa/test_commits.py
- qa/test_config.py
- qa/test_gitlint.py
- qa/test_hooks.py
- qa/test_stdin.py
- qa/test_user_defined.py
- requirements.txt
- run_tests.sh
- setup.py
- test-requirements.txt
This changes various dependencies and test-related files.
* Updates the `pylint` dependency which allows us to run the linting tests with Python 3.6
* Fixes a few warnings emitted after updating `pylint`
* Updates other dependencies such as `sh` and `pytest` (needed for Python 3.7 compatibility)
* Adds Travis CI tests using Python 3.7
* Fixes intermittent test failures in Travis CI (fixes #77)
* Enables all tests for all Python versions in Travis CI
* The failing test for Python 3.7 (using an Ubuntu Xenial image) should be fixed by #79
> Various test fixes, enable linting in CI, add Python 3.7 compatibility

- docs/configuration.md
- gitlint/cli.py
- gitlint/config.py
- gitlint/tests/test_cli.py
This feature is beneficial when running in automated environments
liek CI servers. Current heuristic fails in some conditions.
With this flag enabled we can simply always ignore stdin
and fall back to using target repo.
Closes #56
Needs further discussion, especially regarding actual naming of flag (maybe disregard_stdin would be better idea), test coverage and docs examples.
Feature itself is kind of "meh, boring" :) .
> Initial implementation of 'ignore-stdin' flag

- .travis.yml
- CHANGELOG.md
- Vagrantfile
- docs/contributing.md
- docs/index.md
- qa/requirements.txt
- requirements.txt
- run_tests.sh
- setup.py
Python 3.4 has reached EOL and an increasing number of gitlint's
dependencies have dropped support which makes it hard to maintain.
> Drop support for Python 3.4

- gitlint/cli.py
- gitlint/git.py
- gitlint/tests/expected/test_cli/test_debug_1
- gitlint/tests/test_cli.py
- gitlint/tests/test_git.py
- qa/expected/test_config/test_config_from_file_debug_1
Gitlint now defers reading information from a local git repository until a
certain git property is accessed for the first time.
This will allow us to expose more git repository properties for
rules to consume without incurring a performance penalty when those properties
are not used.
In addition, reading the required info when it's needed rather
than up front avoids adding delay during gitlint startup time and reduces
gitlint's memory footprint.
> Local commit lazy evaluation

- docs/user_defined_rules.md
- examples/my_commit_rules.py
- gitlint/git.py
- gitlint/tests/test_git.py
- gitlint/utils.py
- qa/expected/test_user_defined/test_user_defined_rules_1
- qa/expected/test_user_defined/test_user_defined_rules_with_config_1
- qa/test_user_defined.py
Each GitCommit object now contains a 'branches' property that can be
used as part of rules.
Also added an extra user-defined rule example that demonstrates this.
This implements #108
> GitCommit branches property

- gitlint/files/commit-msg
- qa/test_hooks.py
This will tell gitlint to fetch additional meta-info when linting the
passed commit message.
> Commit-msg hook now uses --staged flag

- .github/workflows/checks.yml
- .travis.yml
- gitlint/shell.py
- qa/shell.py
Trying out CI using Github Actions - plan is to eventually move away
from TravisCI.
Currently still using TravisCI to deal with unit test coverage reporting
(there are some issues with GH actions and coveralls.io).
On windows, we deliberately allow some tests to fail - these are known
issues on windows.
> CI using Github Actions

- .github/workflows/checks.yml
Previously we directly invoked pytest, using run_tests.bat is cleaner.
> Use tools\windows\run_tests.bat in Github Actions

- docs/contrib_rules.md
- gitlint/contrib/rules/conventional_commit.py
- gitlint/tests/config/test_config.py
- gitlint/tests/contrib/test_conventional_commit.py
- gitlint/tests/expected/test_cli/test_contrib_1
- qa/expected/test_contrib/test_contrib_rules_1
This adds "ci" and "build" to the list of allowed conventional commit types.
This completes the list of possible commit message types listed under bullet point 4 in https://www.conventionalcommits.org/en/v1.0.0/#summary.
> Added 'ci' and 'build' to conventional commit types

- CHANGELOG.md
- docs/user_defined_rules.md
- gitlint/config.py
- gitlint/options.py
- gitlint/rules.py
- gitlint/tests/base.py
- gitlint/tests/test_options.py
The RegexOption allows regular expressions to be pre-validated at gitlint
startup and compiled only once which is much more efficient when re-using the
regex (e.g. linting multiple commits).
Replaced StrOption with RegexOption in all rules using regular expressions.
Also made some minor improvements to other Options tests.
> RegexOption option type

- CHANGELOG.md
- docs/rules.md
- gitlint/config.py
- gitlint/files/gitlint
- gitlint/rules.py
- gitlint/tests/expected/test_cli/test_debug_1
- gitlint/tests/expected/test_cli/test_input_stream_debug_2
- gitlint/tests/expected/test_cli/test_lint_staged_msg_filename_2
- gitlint/tests/expected/test_cli/test_lint_staged_stdin_2
- gitlint/tests/rules/test_body_rules.py
- gitlint/tests/samples/commit_message/no-violations
- gitlint/tests/test_lint.py
- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_commits/test_lint_staged_stdin_1
- qa/expected/test_config/test_config_from_file_debug_1
The body-match-regex rule allows users to enforce that the commit-msg
body matches a given regex.
Closes #130
> New Rule: body-match-regex

- gitlint/git.py
- gitlint/tests/git/test_git_commit.py
- qa/base.py
- qa/shell.py
- qa/test_gitlint.py
An attempt to make #148 a little less severe. `git` failing to retrieve these configuration variables is still fatal, but at least the error message is a little nicer.
> Fail nicer when username missing

- CHANGELOG.md
- docs/configuration.md
- gitlint/cli.py
- gitlint/config.py
- gitlint/tests/config/test_config_precedence.py
- qa/base.py
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/test_config.py
Many command-line flags can now also be set through environment variables
following the format GITLINT_<commandline_option>
> Configuration through environment variables

- tools/windows/create-test-repo.bat
Previously, the date parsing in create-test-repo.bat was locale depend,
which tended to cause issues.
This fix uses python for date parsing which is much more reliable.
> Fix: correct date parsing in create-test-repo.bat

- gitlint/tests/test_utils.py
- gitlint/utils.py
When specifying an unknown encoding on windows via the LC_ALL, LC_CTYPE or LANG
environment variables, gitlint will known fallback to UTF-8 instead of
crashing. This is a common scenario when using the commit-msg hook.
Relates to #96
> Improved UTF-8 unicode fallback on windows

- docs/demos/asciicinema.json
- gitlint/cli.py
- gitlint/tests/expected/cli/test_cli_hooks/test_hook_config_1_stdout
- gitlint/tests/expected/cli/test_cli_hooks/test_hook_edit_1_stdout
- gitlint/tests/expected/cli/test_cli_hooks/test_hook_local_commit_1_stdout
- gitlint/tests/expected/cli/test_cli_hooks/test_hook_no_1_stdout
- gitlint/tests/expected/cli/test_cli_hooks/test_hook_no_tty_1_stdout
- gitlint/tests/expected/cli/test_cli_hooks/test_hook_stdin_violations_1_stdout
- gitlint/tests/expected/cli/test_cli_hooks/test_hook_yes_1_stdout
- qa/test_hooks.py
If the silent option was enabled, no violations were printed.
The error message then referred to non-existing "above violations".
> Error message was confusing with silent enabled.

- docs/contrib_rules.md
- docs/rules.md
- docs/user_defined_rules.md
- examples/my_commit_rules.py
- gitlint/contrib/rules/signedoff_by.py
- gitlint/tests/contrib/rules/test_signedoff_by.py
- gitlint/tests/expected/cli/test_cli/test_contrib_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_contrib/test_contrib_rules_1
- qa/expected/test_contrib/test_contrib_rules_with_config_1
- qa/expected/test_user_defined/test_user_defined_rules_examples_1
- qa/expected/test_user_defined/test_user_defined_rules_examples_2
- qa/expected/test_user_defined/test_user_defined_rules_examples_with_config_1
git 2.30: `git commit -s` adds a `Signed-off-by` line, not a `Signed-Off-By`.
> compatibility with 'git commit -s'

- gitlint/rules.py
- gitlint/tests/rules/test_body_rules.py
A body could be crafted with multiple new lines and it would bypass
the body missing rule
It fixes: #176
> Fix missing body rules with multiple new lines

- gitlint/utils.py
pylint is not able to find the member statically. It means that the
lookup member is created dynamically in the pypy implementation
> Fix pypy pylint(no-member) failure in CI

- qa/requirements.txt
- requirements.txt
- setup.py
- test-requirements.txt
wheel:            0.35.1 -> 0.36.2
arrow:            0.17.0 -> 1.0.2
Test dependencies:
pytest:           6.1.2  -> 6.2.2
coverage:         5.3    -> 5.5
radon:            4.3.2  -> 4.4.0
pylint:           2.6.0  -> 2.7.2
python-coveralls: 2.9.2  -> 2.9.3
> Various dependency upgrades

- .coveragerc
This ensures that code which significantly reduces the coverage won't be
accepted.
> tests: Set minimum test coverage

- gitlint/contrib/rules/conventional_commit.py
- gitlint/tests/cli/test_cli.py
- gitlint/tests/contrib/rules/test_conventional_commit.py
- gitlint/tests/expected/cli/test_cli/test_contrib_1
- qa/expected/test_contrib/test_contrib_rules_1
- qa/expected/test_contrib/test_contrib_rules_with_config_1
- qa/test_contrib.py
Following conventional commits docs.
[Commit message with ! to draw attention to breaking change](https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with--to-draw-attention-to-breaking-change)
fixes: #186 #185
> Allow "!" for breaking change commits

- docs/configuration.md
- docs/index.md
- gitlint/cli.py
- gitlint/config.py
- gitlint/files/gitlint
- gitlint/tests/base.py
- gitlint/tests/cli/test_cli.py
- gitlint/tests/config/test_config.py
- gitlint/tests/expected/cli/test_cli/test_debug_1
- gitlint/tests/expected/cli/test_cli/test_input_stream_debug_2
- gitlint/tests/expected/cli/test_cli/test_lint_staged_msg_filename_2
- gitlint/tests/expected/cli/test_cli/test_lint_staged_stdin_2
- gitlint/tests/expected/cli/test_cli/test_named_rules_2
- qa/base.py
- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_commits/test_lint_staged_stdin_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/expected/test_config/test_config_from_file_debug_1
- qa/test_commits.py
- qa/test_config.py
Gitlint will now hard fail when passing an empty commit range via --commits and specifying the --fail-without-commits option.
>  Implements --fail-without-commits option

- docs/index.md
- gitlint/cli.py
- gitlint/git.py
- gitlint/tests/cli/test_cli.py
- gitlint/tests/expected/cli/test_cli/test_lint_commit_1
- gitlint/tests/git/test_git_commit.py
- qa/test_commits.py
Support for new convenience CLI flag `--commit` which allows for each
linting of a single commit.
Implements #141
> Lint single commit using --commit

- setup.py
For easy/"standard" access from the PyPI project page.
`Changelog` matches the title of the linked doc here, and is one of
the recognized names that get the distinctive icon:
https://github.com/pypa/warehouse/blob/64102a6a41f024e54bc0cfe52201d44bc80afd17/warehouse/templates/packaging/detail.html#L24
An example how it looks can be found e.g. in https://pypi.org/project/black/
> Add changelog project URL to project metadata

- docs/configuration.md
- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/tests/cli/test_cli.py
Most of the gitlint command-line options have corresponding environment
variables following the format GITLINT_<commandline_option>, added in
69aa5ffaeb7dae849f8ab655ea0426e26deee44f.
---
The only remaining command-line option that's missing a corresponding environment variable is the `-c` option for overriding individual configuration options.
Additionally, I made the assumption in the documentation that this change would get released in 1.16.0.
I investigated adding tests, but I chose not to for a few, opinionated, reasons
* This is a quite small change, that follows an existing pattern
* The most similar environment variable, `GITLINT_EXTRA_PATH`, does not have a test
* I did not find a clean way to add a meaningful test, but I'm not very experienced with Python testing methods that …
> Add missing environment variable for config file

- gitlint-core/gitlint/tests/cli/test_cli_hooks.py
Without this the test will fail if the `EDITOR` env var is set to
something different than `vim -n`.
> Unset EDITOR env var in test_run_hook_edit

- .github/workflows/checks.yml
- gitlint-core/gitlint/git.py
- gitlint-core/gitlint/tests/cli/test_cli_hooks.py
- gitlint-core/gitlint/tests/git/test_git.py
- qa/test_gitlint.py
- test-requirements.txt
fixes #189.
It uses `git branch --show-current` to get current branch when the old way (`git rev-parse --abbrev-ref HEAD`) fails.
> fix: Not fail when current branch has no commits.

- docs/configuration.md
- docs/index.md
- docs/user_defined_rules.md
- gitlint-core/gitlint/config.py
- gitlint-core/gitlint/files/gitlint
- gitlint-core/gitlint/git.py
- gitlint-core/gitlint/lint.py
- gitlint-core/gitlint/tests/config/test_config.py
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_debug_1
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_input_stream_debug_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_msg_filename_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_stdin_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_named_rules_2
- gitlint-core/gitlint/tests/git/test_git_commit.py
- gitlint-core/gitlint/tests/samples/commit_message/fixup_amend
- gitlint-core/gitlint/tests/test_lint.py
- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_commits/test_lint_staged_stdin_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/expected/test_config/test_config_from_file_debug_1
- qa/test_gitlint.py
This includes:
- a new config option `general.ignore_fixup_amend_commit`
- fixup=amend detection as part of commit.is_fixup_amend_commit
- skipping fixup=amend commits during linting
- Updated docs and tests
This fixes #318
> Support for fixup=amend:<sha> commands

- gitlint-core/gitlint/cli.py
This fixes encoding issues which occur more commonly when invoking the
commit-msg hook on Windows.
Fixes #310
> Bugfix: use DEFAULT_ENCODING for --msg-filename

- .github/workflows/checks.yml
Previously was still running on python 3.6, bumped to 3.10
> CI: Python version bump for windows tests

- gitlint-core/gitlint/git.py
- gitlint-core/gitlint/tests/cli/test_cli.py
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_debug_1
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_input_stream_debug_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_msg_filename_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_stdin_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_named_rules_2
- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_commits/test_lint_staged_stdin_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/expected/test_config/test_config_from_file_debug_1
- qa/expected/test_gitlint/test_commit_binary_file_1
Also ensure commit.parents is empty instead [''] (list with empty
string) when the commit has no parents.
> Add commit parent hashes in debug output

- docs/configuration.md
- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/config.py
- gitlint-core/gitlint/deprecation.py
- gitlint-core/gitlint/files/gitlint
- gitlint-core/gitlint/lint.py
- gitlint-core/gitlint/rules.py
- gitlint-core/gitlint/tests/base.py
- gitlint-core/gitlint/tests/config/test_config.py
- gitlint-core/gitlint/tests/config/test_config_precedence.py
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_debug_1
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_input_stream_debug_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_msg_filename_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_stdin_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_named_rules_2
- gitlint-core/gitlint/tests/rules/test_configuration_rules.py
- gitlint-core/gitlint/tests/rules/test_meta_rules.py
- gitlint-core/gitlint/tests/test_deprecation.py
- qa/expected/test_commits/test_ignore_commits_1
- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_commits/test_lint_staged_stdin_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/expected/test_config/test_config_from_file_debug_1
- qa/expected/test_gitlint/test_commit_binary_file_1
Support for `general.regex-style-search` option which determines regex semantics for 
- author-valid-email
- ignore-by-title
- ignore-by-body
- ignore-body-lines
- ignore-by-author-name
Also includes a new `Deprecation` class to globally implement deprecation behavior and warnings.
> Support for general.regex-style-search

- docs/configuration.md
- docs/contrib_rules.md
- docs/contributing.md
- docs/index.md
I noticed that some links in the docs were broken, so I fixed them in this PR.
To verify the links, I used [markdown-link-check](https://github.com/tcort/markdown-link-check).
I also removed some trailing whitespace in the docs.
> Cleanup docs

- .github/workflows/checks.yml
GitHub Actions unfortunately runs the *latest* version of the actions which fits the `uses` directive version. So right now `actions/checkout@v3` is equivalent to `actions/checkout@v3.0.2`, but this can change at any time. To avoid workflows suddenly failing in case a new minor/patch version of an action, this PR uses the most specific version number available for the checkout action.
> fix: Use specific checkout action version

- .github/workflows/checks.yml
- gitlint-core/gitlint/tests/test_utils.py
- gitlint-core/gitlint/utils.py
Future goal is to remove the sh dependency entirely from gitlint-core.
For now, the use of sh can be re-enabled using GITLINT_USE_SH_LIB=1.
> Disable use of sh library by default

- .github/workflows/checks.yml
- CHANGELOG.md
Python 3.11 was released on 2022-10-24, enable support in CI for
the final 3.11 release (was RC2 before).
> Python 3.11 release support

- docs/index.md
Make it clearer that --commits can be used to lint commits on a specific
branch.
Closes #259
> Docs: clarify using --commits to lint branches

- docs/configuration.md
- docs/index.md
- gitlint-core/gitlint/cli.py
I was wondering why I'd need to set `user.name` and `user.email` when running gitlint with pre-commit in CI, and realized it's because of `--staged` in the hook's default config. It wasn't immediately clear to me why I'd want `--staged` (turns out I don't), so I thought I'd document it.
Might be nice to also document that with `--staged` one needs those git configs set, but don't know if that's too much detail on this level.
> Document when one would want to use --staged

- docs/contrib_rules.md
- gitlint-core/gitlint/contrib/rules/authors_commit.py
- gitlint-core/gitlint/tests/contrib/rules/test_authors_commit.py
- gitlint-core/gitlint/tests/samples/config/AUTHORS
It is possible to manage a so-called [AUTHORS](https://opensource.google/documentation/reference/releasing/authors) file in the repository. In this file, all committers for the respective project are listed.
With this `gitlint` rule, it can be ensured that only people who are listed in the AUTHORS file can commit.
> Add authors-commit contrib rule

- .pre-commit-hooks.yaml
- docs/index.md
gitlint cannot be run easily via pre-commit inside a CI without pre-commit configuration for the commit stage
https://github.com/jorisroovers/gitlint/issues/191
> Add a commit or manual stage to pre-commit hook config

- Dockerfile
This is required for git=>2.35.2 (Fix for CVE-2022-24765).
This fixes #365
> Dockerfile: add /repo as safe git repo

- .github/dependabot.yml
Previously, dependabot only monitored top-level gitlint dependencies, but
not gitlint-core dependencies.
> Dependabot: also monitor gitlint-core

- .github/workflows/checks.yml
This avoids running jobs twice and unneccessarily running gitlint
against in-progress work.
> CI: only run on PR and push to main

- .github/workflows/checks.yml
This adds a GHA job that reliably determines if all the required dependencies have succeeded or not.
It also allows to reduce the list of required branch protection CI statuses to just one — `check`. This reduces the maintenance burden by a lot and have been battle-tested across a small bunch of projects in its action form and in-house implementations of other people.
It is now in use in aiohttp (and other aio-libs projects), CherryPy, attrs, coveragepy, conda some of the Ansible repositories, pip-tools, pydantic, spaceship-prompt, Towncrier, all of the jaraco's projects (like `setuptools`, `importlib_metadata`), some PyCQA, PyCA, PyPA and pytest projects, a few AWS Labs projects.
The story behind this is explained in more detail at https://github.com/marketplace/actions/alls-green#why.
> Introduce a gate/check GHA job

- .gitlint
Dependabot tends to generate "Co-authored-by" lines that exceed the default
80 char limit. Ignore those lines in commit messages.
> gitlint: ignore dependabot Co-authored-by lines

- .github/workflows/checks.yml
- docs/index.md
- gitlint-core/setup.py
- setup.py
- test-requirements.txt
Bumped minimal python version in setup.py to 3.7.
Updated docs and test-requirements.txt accordingly.
> Drop support for Python 3.6

- .gitlint
We were only ignoring Co-authored-by lines for dependabot commits
before, but that sometimes still causes gitlint violations on other lines.
With this changes, we're ignore the entire commit message for commits
generated by dependabot.
> Ignore dependabot commits entirely

- .github/workflows/checks.yml
- gitlint-core/gitlint/tests/cli/test_cli.py
- gitlint-core/gitlint/tests/cli/test_cli_hooks.py
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_debug_1
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_msg_filename_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_stdin_2
Fix failing unit tests on Windows.
Run all unit tests in Windows in CI.
This fixes #92
> Fix Windows unit tests

- .github/workflows/checks.yml
- pyproject.toml
- qa/base.py
- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/expected/test_config/test_config_from_file_debug_1
- qa/expected/test_gitlint/test_commit_binary_file_1
- qa/shell.py
- qa/test_commits.py
- qa/test_config.py
- qa/test_gitlint.py
- qa/test_stdin.py
- qa/utils.py
New attempt to fix integration tests on windows
> Fix integration tests on windows

- .github/workflows/checks.yml
- qa/test_hooks.py
> Integration tests: fix 2 hooktests on windows

- README.md
- docs/index.md
Gitlint has run well on Windows for years now, eventhough we still have
some unicode issues to resolve.
> Docs: Remove experimental wording for Windows support

- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/tests/cli/test_cli.py
- gitlint-core/gitlint/tests/cli/test_cli_hooks.py
- gitlint-core/gitlint/tests/git/test_git_commit.py
- pyproject.toml
- qa/samples/user_rules/extra/extra_rules.py
- qa/shell.py
Also fixes a few items that were marked as issues by ruff.
> Use ruff for linting

- docs/index.md
- gitlint-core/gitlint/cli.py
- qa/test_commits.py
In order to avoid applications needing to select between `--commit` and `--commits` based on the number of commits, allow for providing a single commit with `--commits` in the format:
```
$ gitlint --commits <sha>,
```
The trailing comma ensures that gitlint knows this is a commit list and not a refspec.
Signed-off-by: Carles Cufi <carles.cufi@nordicsemi.no>
> cli: Allow for a single commit in the --commits cmd-line param

- .github/workflows/publish-release.yml
- .github/workflows/test-release.yml
Currently only builds packages, follow-up will also publish to test.pypi.org.
Also renames the Test Release workflow (and some vars in it).
> GHA: Publish release workflow

- .github/workflows/publish-release.yml
- .github/workflows/test-release.yml
Allow for on-demand publishing of the main branch to test.pypi.org.
> GHA: Publish release to test.pypi.org on demand

- pyproject.toml
Without this line, the gitlint wheel is missing it's dependency on
gitlint-core.
> Add missing metadata hook config in pyproject.toml

- .github/workflows/publish-release.yml
- .github/workflows/test-release.yml
Automatically run integration tests on newly released packages.
> GHA: Call test-release after publish-release workflow

- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/config.py
- gitlint-core/gitlint/hooks.py
- gitlint-core/gitlint/shell.py
- gitlint-core/gitlint/tests/base.py
- gitlint-core/gitlint/tests/cli/test_cli.py
- gitlint-core/gitlint/tests/cli/test_cli_hooks.py
- gitlint-core/gitlint/tests/test_utils.py
- gitlint-core/gitlint/utils.py
- qa/test_gitlint.py
Distinguish between terminal encoding (DEFAULT_ENCODING) and file
encoding (FILE_ENCODING).
Before, gitlint always decoded files using the terminal encoding
(DEFAULT_ENCODING) which can be problematic in cases where the terminal
encoding is non UTF-8.
File encoding is hard set to UTF-8.
> Separate FILE_ENCODING from TERMINAL_ENCODING

- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/tests/cli/test_cli.py
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_debug_1
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_input_stream_debug_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_msg_filename_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_stdin_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_named_rules_2
- qa/base.py
- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_commits/test_lint_staged_stdin_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/expected/test_config/test_config_from_file_debug_1
- qa/expected/test_gitlint/test_commit_binary_file_1
- qa/shell.py
- qa/test_stdin.py
- qa/utils.py
Renames DEFAULT_ENCODING to TERMINAL_ENCODING in the debug output.
Adds FILE_ENCODING to the debug output.
> Debug: Rename DEFAULT_ENCODING to TERMINAL_ENCODING, add FILE_ENCODING

- .github/workflows/checks.yml
- .github/workflows/publish-release.yml
- .github/workflows/test-release.yml
Also perform hatch download before gitlint install in test-release
workflow. This buys us a little more time for the package to show up on
PyPI before trying to install and test it.
> GHA: Auto publish dev build on main

- .github/workflows/checks.yml
When invoking the publish-release from the checks workflows on main,
pass all secrets. This is required for PYPI secrets to be available.
> GHA: Pass secrets to publish-release workflow

- README.md
This should ensure the screenshot is correctly displayed on PyPI.
> Use absolute path for README screenshot

- .github/workflows/publish-release.yml
- .github/workflows/test-release.yml
It takes a short time for packages to show up on PyPI after publishing.
Wait for the gitlint package to show up before starting the post-release
test run by trying to install the gitlint package, and retrying after a
timeout until the package is available.
> GHA: Wait for gitlint package to be available after publish

- .github/workflows/publish-release.yml
- .github/workflows/test-release.yml
This will increase the odds of PYPI package replication to all servers having
finished.
> GHA: Additional sleep in wait-for-package

- .github/workflows/publish-release.yml
By increasing the timeout to 10min, we further increase the odds that PYPI
package replication to all servers has finished before triggering the
test-release workflow.
> GHA: Increase post publish PYPI wait timeout to 10min

- pyproject.toml
This enables traceability from the build to the source code.
> Add metadata urls to source commit

- gitlint-core/pyproject.toml
- pyproject.toml
This enables traceability from the build to the source code for
gitlint-core.
> Metadata urls to source commit for gitlint-core

- hatch_build.py
This allows for re-use of the 'dev' environment between different git branches.
> Disable gitlint to gitlint-core versioning matching in dev env

- docs/contributing.md
Adds a section to the Contributing docs that explains how to install dev
builds.
> Docs: explain dev builds

- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/rules.py
- gitlint-core/gitlint/tests/rules/test_configuration_rules.py
If the user has an ignore-by-author-name rule configured, and when manually
passing a git commit message to gitlint using --msg-filename or via STDIN
without also using the --staged flag, gitlint crashes because
commit.author_name is unknown.
This fix will print a warning instead and skip the rule.
Fixes #403.
> Bugfix: ignore-by-author-name crashes without --staged

- qa/base.py
- qa/expected/test_user_defined/test_user_defined_rules_examples_2
- qa/test_user_defined.py
Modern git does commit message cleanup by default (e.g. removing trailing
whitespace). We disable this during integration testing by setting:
git config commit.cleanup=verbatim
> Integration tests: set git config commit.cleanup=verbatim

- qa/expected/test_rules/test_ignore_rules_1
- qa/expected/test_rules/test_ignore_rules_2
- qa/expected/test_rules/test_match_regex_rules_1
- qa/test_rules.py
Integration tests for rules that use regexes.
The targetted rules don't really do anything unless they have a custom
regex set. Since a default gitlint run doesn't meaningfully tests these
rules, explicit tests for these rules ensure they work properly.
> Integration tests: test match regex and ignore rules

- .github/workflows/checks.yml
- .github/workflows/publish-release.yml
- docs/contributing.md
Before only publishing to test.pypi.org was supported, now also to
pypi.org.
Autopublishing on every commit to main still happens to test.pypi.org.
> GHA: Enable publishing packages to pypi.org

- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/expected/test_config/test_config_from_file_debug_1
- qa/expected/test_gitlint/test_commit_binary_file_1
This broke the tests on windows before, checking whether it still does.
> Integration Tests: remove harcoded UTF-8 terminal encoding

- .github/workflows/publish-docker.yml
This allows for the gitlint docker image to be build and pushed
on-demand.
> GHA: publish-docker workflow

- gitlint-core/gitlint/__init__.py
- gitlint-core/gitlint/git.py
- gitlint-core/gitlint/rule_finder.py
- gitlint-core/gitlint/tests/base.py
- gitlint-core/gitlint/tests/cli/test_cli.py
- gitlint-core/gitlint/tests/contrib/rules/test_authors_commit.py
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_multiple_commits_csv_1
- gitlint-core/gitlint/tests/rules/test_configuration_rules.py
- gitlint-core/gitlint/tests/rules/test_rules.py
- gitlint-core/gitlint/tests/rules/test_user_rules.py
- gitlint-core/gitlint/tests/samples/user_rules/my_commit_rules.py
- gitlint-core/gitlint/tests/samples/user_rules/parent_package/__init__.py
- gitlint-core/gitlint/tests/test_hooks.py
- gitlint-core/gitlint/tests/test_options.py
- pyproject.toml
Improves and fixes some existing unit tests.
Adds a few new tests.
> Improve unit test coverage

- .github/workflows/github-release.yml
- .github/workflows/publish-release.yml
A new GHA workflow that publishes gitlint when new gitlint releases are
created on github.
> GHA: github release workflow

- CHANGELOG.md
This release was primarily focussed on modernizing gitlint's build and test
tooling (details: #378).
General
Python 3.6 no longer supported (EOL since 2021-12-23) (#379)
This is the last release to support the sh library (used under-the-hood to
execute git commands) by setting GITLINT_USE_SH_LIB=1. This is already
disabled by default since v0.18.0.
Features
Allow for a single commit in the --commits cmd-line param (#412)
Gitlint now separates FILE_ENCODING (always UTF-8) from TERMINAL_ENCODING
(terminal dependent), this should improve issues with unicode. Use
gitlint --debug to inspect these values. (#424)
Bugfixes
ignore-by-author-name crashes without --staged (#445)
Various documentation fixes (#401, #433) - Thanks scop
Development
Adopted hatch for project management (#384). This …
> 0.19.0 release

- gitlint-core/LICENSE
- gitlint-core/README.md
- gitlint-core/pyproject.toml
- pyproject.toml
Temporarily comment out dynamic URLs using the `commit_hash` variable in the
tool.hatch.metadata.hooks.vcs.urls section in pyproject.toml.
Required to fix builds from sdist.
Relates to #460
> Remove hatch-vcs metadata hook that uses commit_hash

- .github/workflows/ci.yml
- .github/workflows/publish-release.yml
This patch switches the CI/CD workflows to use the PyPA-endorsed PEP 517 build front-end called `build`. It is called without `--sdist` and `--wheel` CLI options, in which case `build` creates an sdist from the Git checkout but the following wheel build is made from that sdist tarball as opposed to using the Git checkout.
This has a side effect of smoke-testing that it's possible to build wheels from the published sdists. And this is the flow that `pip install` follows when it's requested to install from an sdist.
Ref: https://github.com/jorisroovers/gitlint/issues/460#issuecomment-1462121899
> 🧪🔧 Switch to using `pypa/build` in CI

- CHANGELOG.md
- Fix issue that prevented homebrew packages from being built (#460)
- Switch to using pypa/build in CI (#463)
Full Release details in CHANGELOG.md.
> 0.19.1 release

- .github/workflows/publish-release.yml
This patch switches away from using `hatch publish` to the PyPA GitHub action that performs distribution publishing using Twine.
Resolves: #465.
> Publish to (Test)PyPI @ GHA using `pypi-publish`

- .github/workflows/ci.yml
- .github/workflows/test-release.yml
- gitlint-core/gitlint/shell.py
- gitlint-core/gitlint/tests/test_utils.py
- gitlint-core/gitlint/utils.py
- gitlint-core/pyproject.toml
Removes the dependency on the `sh` library, which has been disabled and
deprecated since 0.18.0.
> Remove sh library

- gitlint-core/pyproject.toml
- pyproject.toml
- Correctly increase dev versions when micro tag versions are present
- Removes the need to maintain dev tags
Relates to #456
> Switch hatch-vcs version scheme to release-branch-semver

- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/tests/cli/test_cli.py
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_debug_1
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_input_stream_debug_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_msg_filename_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_stdin_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_named_rules_2
- qa/base.py
- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_commits/test_lint_staged_stdin_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/expected/test_config/test_config_from_file_debug_1
- qa/expected/test_gitlint/test_commit_binary_file_1
With the removal of the `sh` libary from gitlint, the GITLINT_USE_SH_LIB
environment variable is no longer meaningful and neither has logging its value.
> Remove GITLINT_USE_SH_LIB debug logging

- pyproject.toml
Before this patch, we didn't run black as part of autofix if `ruff
--fix` returned an error. This patch ensures the exit status of `ruff
--fix` is ignored and black always runs.
> Hatch autofix script: always run black

- gitlint-core/gitlint/cache.py
- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/config.py
- gitlint-core/gitlint/deprecation.py
- gitlint-core/gitlint/display.py
- gitlint-core/gitlint/git.py
- gitlint-core/gitlint/lint.py
- gitlint-core/gitlint/options.py
- gitlint-core/gitlint/rules.py
- gitlint-core/gitlint/shell.py
- gitlint-core/gitlint/tests/rules/test_rules.py
Converts existing classes to dataclasses where applicable.
> Dataclasses

- gitlint-core/gitlint/rules.py
Remove the unused `Rule._log_deprecated_regex_style_search` class
variable.
> Remove unused class variable

- .devcontainer/postCreateCommand.sh
- docs/contributing.md
The docs were missing important steps on how to test gitlint against
different python versions on the dev container.
Also fixes the Devcontainer's postCreateCommand.sh to install hatch
using pip instead of homebrew.
> Docs: info on testing different python versions

- .devcontainer/devcontainer.json
- .github/workflows/ci.yml
- docs/contributing.md
- gitlint-core/gitlint/cache.py
- gitlint-core/gitlint/cli.py
- gitlint-core/gitlint/config.py
- gitlint-core/gitlint/contrib/rules/authors_commit.py
- gitlint-core/gitlint/rules.py
- gitlint-core/gitlint/utils.py
- pyproject.toml
- qa/utils.py
- Adds mypy for type checking, runs in CI on every commit.
- Configures mypy for gitlint (excludes, ignores, tuned strictness)
- Fixes several typing issues
- Updates contributing docs with how to use mypy
> Static type checking using mypy

- .github/workflows/publish-release.yml
Replace token based authentication with OIDC for PyPI package
publishing.
Relates to #467
> GHA: Use PyPI OIDC for publishing

- .github/workflows/ci.yml
- .github/workflows/publish-release.yml
- .github/workflows/test-release.yml
Replace if statements with ${{ vars.PYPI_TARGET }}, defined in
GHA environments, to select the target PyPI repository when publishing
packages.
Relates to #467
Implements #466
> GHA: Use GHA environments to select PyPI target

- docs/extra.css
- docs/extra.js
- docs/index.md
- docs/termynal.css
- docs/termynal.js
- mkdocs.yml
Replaces ASCII Cinema demo with Termynal, allowing mocking the demo
rather than use a CLI recording which is error prone, slow and difficult to
edit and maintain.
> WIP: Termynal

- mkdocs.yml
Adds an anchor link at the end of each headline.
> Docs: enable toc extension

- README.md
Maintenance is under control, we can put this message back in the future
if required.
> Remove looking for contributors message in README

- .github/workflows/ci.yml
- mkdocs.yml
- pyproject.toml
New `docs:validate` hatch script:
- Check whether the docs build correctly
- Validate external URLs in docs using [linkchecker](https://github.com/linkchecker/linkchecker).
Runs on every commit in CI.
> CI: Docs validate

- tools/create-test-repo.sh
tools/create-test-repo.sh will now enter a subshell
immediately inside the temporary git repo directory, and reconfigure
hatch to be able to run from that that directory.
This avoids developers having to manually type the cd command to enter
the correct temp repo after creation and having to reconfigure hatch.
> tools/create-test-repo.sh: use subshell

- .github/workflows/ci.yml
- .github/workflows/publish-docs.yml
- Change incorrect --deploy parameter to --push
- Allow for manual trigger of workflow
- Call publish-docs workflow from ci workflow when committing on main
> GHA: Improvements for auto-deploy docs

- .devcontainer/postCreateCommand.sh
- .github/workflows/ci.yml
- .github/workflows/publish-docs.yml
- .github/workflows/publish-release.yml
- .github/workflows/test-release.yml
- docs/contributing/environment_setup.md
> Upgrade Hatch to 1.7.0

- docs/contributing/releases.md
- docs/installation.md
Explains to how install gitlint using github archive URLs.
Docs for #464
> Docs: Support for git archive installs

- .github/workflows/ci.yml
Smoke test sdist tarballs (gitlint and gitlint-core) for downstream packaging:
- Upload and re-downloading them in a separate job
- Extract the tarballs and rebuild wheels using pypa/build
- Install the wheels
- Run gitlint to ensure everything its not failing
Closes #468
> GHA: Smoke test sdist package for downstream packaging

- .github/workflows/ci.yml
When using github.rest.issues.createComment, context.issue.number
does not work when the notify job is triggered by a push to the 'main'
branch event.
Instead, we manually extract the PR number using the gh CLI.
> GHA: Notify - extract PR number when merging on main

- gitlint-core/gitlint/config.py
- gitlint-core/gitlint/tests/config/test_config.py
Implement missing `__repr__` methods where it makes sense.
Not required for dataclasses as they have them already implemented.
Not required for a few classes with only static methods.
This closes #321
> Implement missing repr methods

- docs/configuration/general_options.md
- gitlint-core/gitlint/config.py
- gitlint-core/gitlint/tests/config/test_config.py
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_debug_1
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_input_stream_debug_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_msg_filename_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_lint_staged_stdin_2
- gitlint-core/gitlint/tests/expected/cli/test_cli/test_named_rules_2
- gitlint-core/gitlint/tests/rules/test_configuration_rules.py
- gitlint-core/gitlint/tests/rules/test_meta_rules.py
- gitlint-core/gitlint/tests/test_deprecation.py
- qa/expected/test_commits/test_ignore_commits_1
- qa/expected/test_commits/test_lint_staged_msg_filename_1
- qa/expected/test_commits/test_lint_staged_stdin_1
- qa/expected/test_config/test_config_from_env_1
- qa/expected/test_config/test_config_from_env_2
- qa/expected/test_config/test_config_from_file_debug_1
- qa/expected/test_gitlint/test_commit_binary_file_1
This will make all rules use re.search() by default.
It's still possible to manually reverse this behavior by setting:
general.regex-style-search=False
Relates to #254
> Default to general.regex-style-search=True

- docs/rules/contrib_rules.md
Fixed example in docs for conventional comits contrib rule.
> docs: fix example
